export const jsonData = [
  {
    id: 0,
    section: "phone",
    image: "assets/pixel_5.jpeg",
    otherColor: "assets/pixel5_othercolor1.jpg",
    model: "5",
    url: ["assets/pixel_5.jpeg", "assets/pixel5_othercolor1.jpg"],
    name: "Pixel 5",
    serialNo: "SKU12345-12",
    price: "$ 499",
    priceInNumber: 499,
    feature: "Smart, Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 3.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#E3F7F4",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6.0 heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 1,
    section: "phone",
    model: "6",
    image: "assets/pixel_6.jpg",
    otherColor: "assets/pixel6_othercolor1.jpg",
    url: ["assets/pixel_6.jpg", "assets/pixel6_othercolor1.jpg"],
    name: "Pixel 6",
    serialNo: "RKM45678-45",
    price: "$ 699",
    priceInNumber: 699,
    feature: "Smart",
    rating: "1.2k",
    ratingInNo: 4,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#EBF5F3",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6.0 heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
    processor: "Google Tensor Titan M2 security coprocessor",
  },
  {
    id: 2,
    section: "phone",
    model: "6 pro",
    image: "assets/pixel_6pro.jpg",
    otherColor: "assets/pixel6pro_othercolor1.jpg",
    url: ["assets/pixel_6pro.jpg", "assets/pixel6pro_othercolor1.jpg"],
    name: "Pixel 6 Pro",
    serialNo: "PIX78912-78",
    price: "$ 799",
    priceInNumber: 799,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#F7F7ED",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },

  {
    id: 3,
    section: "headphone",
    model: "Airpod",
    image: "assets/airpod.png",
    otherColor: "assets/airpod.png",
    url: ["assets/airpod.png", "assets/airpod.png"],
    name: "Airpod",
    serialNo: "PIX78912-78",
    price: "$ 199",
    priceInNumber: 199,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#F7F7ED",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 4,
    section: "headphone",
    model: "Headset",
    image: "assets/neckheadphone.png",
    otherColor: "assets/neckheadphone.png",
    url: ["assets/neckheadphone.png", "assets/neckheadphone.png"],
    name: "Headset",
    serialNo: "PIX78912-78",
    price: "$ 299",
    priceInNumber: 299,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#EBF5F3",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 5,
    section: "headphone",
    model: "Over headphone",
    image: "assets/overheadphone.png",
    otherColor: "assets/overheadphone.png",
    url: ["assets/overheadphone.png", "assets/overheadphone.png"],
    name: "Headphone",
    serialNo: "PIX78912-78",
    price: "$ 399",
    priceInNumber: 399,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#E3F7F4",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 6,
    section: "accessories",
    model: "Charger",
    image: "assets/charger.png",
    otherColor: "assets/charger.png",
    url: ["assets/charger.png", "assets/charger.png"],
    name: "Mobile     Charger",
    serialNo: "PIX78912-78",
    price: "$ 59",
    priceInNumber: 59,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#E3F7F4",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 7,
    section: "accessories",
    model: "Temper",
    image: "assets/temper.png",
    otherColor: "assets/temper.png",
    url: ["assets/temper.png", "assets/temper.png"],
    name: "Temper",
    serialNo: "PIX78912-78",
    price: "$ 19",
    priceInNumber: 19,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#EBF5F3",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
  {
    id: 8,
    section: "accessories",
    image: "assets/cover.png",
    otherColor: "assets/cover.png",
    url: ["assets/cover.png", "assets/cover.png"],
    name: "Cover",
    serialNo: "PIX78912-78",
    price: "$ 49",
    priceInNumber: 49,
    feature: "Powerful, Helpful",
    rating: "1.2k",
    ratingInNo: 4.5,
    color: ["Black", "White", "Blue"],
    colorInHex: ["#2D3735", "#E9ECEF", "#219EBC"],
    backgroundColor: "#F7F7ED",
    display: [
      "Full-screen 6.1-inch (156 mm)1 display, up to 60 Hz",
      "20:9 aspect ratio",
      "FHD+ (1080 x 2400) OLED at 429 ppi",
      "Corning® Gorilla® Glass 3™ cover glass",
      "Always-on display with At a Glance and Now Playing",
    ],
    dimension: [
      "6. heightt x 2.8 width x 0.35 depth (in)",
      "152.2 height x 71.8 width x 8.9 depth (mm)",
      "6.3 oz",
      "178 g",
    ],
    battery: [
      "Over 24-hour battery life3",
      "Up to 72-our battery life with Extreme Battery-Saver",
      "Typical 4410 mAh",
      "Fast Charging",
    ],
    memory: "6 GB LPDDR5 RAM",
    storage: "128 GB storage UFS 3.1 storage",
  },
];
