import { createTheme, ThemeProvider } from "@mui/material/styles";
import { makeStyles } from "@mui/styles";

export const createAccountStyle = makeStyles((theme) => ({
  "& .body":{
    margin: "0 !important",
    overflow: "hidden !important",
  },
  "& .root":{
    margin: "0 !important",
    overflow: "hidden !important",
  },
  RoundIconFirst: {
    position: 'absolute',
    top: '-100px',
    left: '100px',
  },
  RoundIconSecond: {
    position: 'absolute',
    top: '0px',
    left: '50px',
    zIndex: '1',
  },
  RoundIconThird: {
    position: 'absolute',
    bottom: '-15px',
    left: '-100px',
  },
  subSection1: {
    backgroundColor: "#FFFFFF !important",
    height: '100vh  !important',
  },

  subSection2: {
    backgroundColor: "#5078E1 !important",
  },
  teamImage: {
    position: 'absolute',
    zIndex: '2 !important',
    bottom: '-30px !important',
    width: '800px !important',
    height: '500px !important',
  },
  input: {
    display: "block !important",
    marginTop: "10px !important",
    marginBottom: "20px !important",
    width: "100% !important",
    padding: "10px !important",
    outline: "none !important",
    "&:hover": {
      backgroundColor: "#219ebc1a !important",
      cursor: "pointer !important",
    },
    "&:focus": {
      border: "0.5px solid #219ebc !important",
      boxShadow: "none !important",
      caretColor: "#219ebc !important",
      cursor: "text !important",
    },
  },
  helperText: {
    color: "#888 !important",
    fontSize: "12px !important",
    marginTop: "5px !important",
  },
  inputUsernameHover: {
    backgroundColor: "#219ebc1a !important",
    cursor: "pointer !important",
  },
  inputUsernameFocus: {
    border: "1px solid #219ebc !important",
    boxShadow: "none !important",
    caretColor: "#219ebc !important",
    cursor: "text !important",
  },
  inputPassword: {
    font: "normal normal 800 14px/18px Montserrat !important",
    letterSpacing: "0px !important",
    color: "#091b29 !important",
    background: "#ffffff 0% 0% no-repeat padding-box !important",
    border: "1px solid #e4e8ee !important",
    borderRadius: "4px !important",
    marginBottom: "7px !important",
  },
  inputPasswordSmallSzie: {
    fontWeight: "600 !important",
  },
  submitButton: {
    font: "normal normal 700 14px/18px Montserrat !important",
    letterSpacing: "0px !important",
    color: "#ffffff !important",
    background: "#219ebc 0% 0% no-repeat padding-box !important",
    boxShadow: "0px 6px 10px #00000014 !important",
    borderRadius: "4px !important",
    borderColor: "transparent !important",
    width: "101% !important",
    padding: "9px !important",
    textAlign: "center",
    cursor: "pointer",
    marginTop: "10px !important",
    marginBottom: "20px !important",
  },
  loginButton: {
    color: "black !important",
    backgroundColor: "transparent !important",
    margin: "auto auto 20px !important",
    font: "normal normal 800 14px/18px Montserrat !important",
    boxShadow: "0px 6px 10px #00000014 !important",
    borderRadius: "4px !important",
    borderColor: "transparent !important",
    width: "30% !important",
    padding: "9px !important",
    textAlign: "center",
    display: "flex",
    position: "relative",
    left: "16px",
    justifyContent: "center",
    cursor: "pointer",
  },
  successCard: {
    position: "fixed !important",
    top: "50% !important",
    left: "50% !important",
    transform: "translate(-50%, -50%) !important",
    backgroundColor: "#ffffff !important",
    padding: "40px !important",
    borderRadius: "8px !important",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.2) !important",
    opacity: "0 !important",
    zIndex: "-1 !important",
    transition: "opacity 0.5s ease-in-out !important",
  },
  successText: {
    font: "normal normal 800 18px/18px Montserrat !important",
  },
  show: {
    zIndex: "10 !important",
    opacity: "1 !important",
  },
  headingWelcome: {
    font: "normal normal 800 24px/29px Montserrat !important",
    fontFamily: "Montserrat, sans-serif !important",
    letterSpacing: "0.14px !important",
    color: "#091b29 !important",
  },
  headingRegister: {
    font: "normal normal 500 18px/22px Montserrat !important",
    letterSpacing: "0.11px !important",
    color: "#bbbbbb !important",
    paddingTop: "10px !important",
    paddingBottom: "25px !important",
  },
  label: {
    font: "normal normal 400 12px/15px Montserrat !important",
    letterSpacing: "0px !important",
    color: "#98a0ac !important",
  },
  inputUsername: {
    font: "normal normal 600 14px/18px Montserrat !important",
    letterSpacing: "0px !important",
    color: "#091b29 !important",
    background: "#ffffff 0% 0% no-repeat padding-box !important",
    border: "1px solid #e4e8ee !important",
    borderRadius: "4px !important",
  },
  containerPassword: {
    position: "relative !important",
    marginBottom: "0px !important",
  },
  eyeIcon: {
    position: "relative !important",
    width: "20px !important",
    cursor: "pointer !important",
    bottom: "35px !important",
    left: "97% !important",
    display: "inline !important",
  },
  errorMessage: {
    font: "normal normal 500 12px/18px Montserrat !important",
    color: "red",
    position: "relative",
    bottom: "15px",
    marginTop: "5px !important",
  },
  passwordError: {
    bottom: "25px",
  },
}));
