export const data = [
  {
    address_details: {
      aline1: "Casagrande apartment",
      aline2: "Indira Nagar",
      area: "Neelankarai",
      city: "Chennai",
      country: "India",
      dno: "12",
      landmark: "Madhya Kailash",
      lang: "",
      lat: "",
      pincode: "600020",
      state: "Tamilnadu",
    },
    contact_details: {
      bphone: "27377323",
      ccode: "+91",
      email: "chan@gmail.com",
      mphone: "848874783",
      stdcode: "044",
      website: "www.google.com",
    },
    property_details: {
      cname: "Organization Name",
      pdesc: "",
      pname: "Casagrande",
      pperiod: "Monthly",
      status: "Active",
    },
    property_details2: {
      carea: "434",
      hdate: "2023-01-01",
      munit: "Sq.ft",
      pets: "false",
      plist: "",
      ppurp: "Residential",
      ptype: "Apartment",
      rtype: "Rent",
      tarea: "500",
      ybuilt: "2020-01-01",
    },
  },



  {
    address_details: {
      aline1: "Apollo apartment",
      aline2: "Old Rajinder Nagar",
      area: "Delhi",
      city: "Chennai",
      country: "India",
      dno: "12",
      landmark: "Hanuman temple",
      lang: "",
      lat: "",
      pincode: "600020",
      state: "Tamilnadu",
    },
    contact_details: {
      bphone: "27377323",
      ccode: "+91",
      email: "chan@gmail.com",
      mphone: "848874783",
      stdcode: "044",
      website: "www.google.com",
    },
    property_details: {
      cname: "Organization Name",
      pdesc: "",
      pname: "Rubix",
      pperiod: "Daily",
      status: "InActive",
    },
    property_details2: {
      carea: "434",
      hdate: "2023-01-01",
      munit: "Sq.ft",
      pets: "false",
      plist: "",
      ppurp: "Residential",
      ptype: "Apartment",
      rtype: "Lease",
      tarea: "500",
      ybuilt: "2020-01-01",
    },
  },


  {
    address_details: {
      aline1: "Casagrande apartment",
      aline2: "Indira Nagar",
      area: "Adyar",
      city: "Chennai",
      country: "India",
      dno: "12",
      landmark: "Madhya Kailash",
      lang: "",
      lat: "",
      pincode: "600020",
      state: "Tamilnadu",
    },
    contact_details: {
      bphone: "27377323",
      ccode: "+91",
      email: "chan@gmail.com",
      mphone: "848874783",
      stdcode: "044",
      website: "www.google.com",
    },
    property_details: {
      cname: "Company Name",
      pdesc: "",
      pname: "Shanthi Illam",
      pperiod: "Monthly",
      status: "Active",
    },
    property_details2: {
      carea: "434",
      hdate: "2023-01-01",
      munit: "Sq.ft",
      pets: "false",
      plist: "",
      ppurp: "Residential",
      ptype: "Individual house",
      rtype: "Lease",
      tarea: "500",
      ybuilt: "2020-01-01",
    },
  },


];
